Uploader: John Doe
UserID: johndoe@lifescience-ri.eu
DatasetID: aa-Dataset-abcde-fghi
DatasetFolder: DATASET_ABC
Email: 
Password: 
APIHost: api.bp.nbis.se
SMTPHost: tickets.nbis.se
SMTPPort: 587
S3Config: 
