apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .JobName }}
  labels: 
    bigpicture: bpctl
    release: {{ .JobReleaseLabel }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        bigpicture: bpctl
        release: {{ .JobReleaseLabel }}
    spec:
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsUser: 65534
      restartPolicy: Never
      containers:
        - name: bpctl
          image: harbor.nbis.se/sda/bpctl:latest
          imagePullPolicy: Always
          args: {{ .JobArgs }}
          env:
            - name: USER_ID
              value: {{ .UserID }}
            - name: DATASET_ID
              value: {{ .DatasetID }}
            - name: DATASET_FOLDER
              value: {{ .DatasetFolder }}
            - name: SSL_CA_CERT
              value: "{{ .SslCaCert }}"
            - name: CLIENT_API_HOST
              value: {{ .ClientAPIHost }}
            - name: CLIENT_ACCESS_TOKEN
              value: {{ .ClientAccessToken }}
            - name: MAIL_UPLOADER_NAME
              value: "{{ .MailUploaderName }}"
            - name: MAIL_UPLOADER_ORGANIZATION_NAME
              value: "{{ .MailUploaderOrganizationName }}"
            - name: MAIL_UPLOADER
              value: {{ .MailUploader }}
            - name: MAIL_ADDRESS
              value: {{ .MailAddress }}
            - name: MAIL_PASSWORD
              value: {{ .MailPassword }}
            - name: MAIL_SMTP_HOST
              value: {{ .MailSMTPHost }}
            - name: MAIL_SMTP_PORT
              value: "{{ .MailSMTPPort }}"
            - name: S3_METADATA_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .StorageSecretName }}
                  key: METADATA_ACCESS_KEY
            - name: S3_METADATA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .StorageSecretName }}
                  key: METADATA_SECRET_KEY
            - name: S3_ARCHIVE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .StorageSecretName }}
                  key: ARCHIVE_ACCESS_KEY
            - name: S3_ARCHIVE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .StorageSecretName }}
                  key: ARCHIVE_SECRET_KEY
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: data-volume
              mountPath: {{ .DataDirectory }}
            {{- if .WithXML }}
            - name: xml-data
              mountPath: {{ .DataDirectory }}/xml
            {{- end }}
            - name: tls
              mountPath: /.secrets/tls/
      volumes:
        - name: data-volume
          emptyDir: {}
        {{- if .WithXML }}
        - name: xml-data
          secret:
            defaultMode: 288
            secretName: {{ .JobName }}-xml-secret
        {{- end }}
        - name: tls
          secret:
            defaultMode: 288
            secretName: {{ .CertSecretName }}
